variable "project_name" {
  description = "Project name used for resource naming and tags."
  type        = string
}

variable "environment" {
  description = "Deployment environment name."
  type        = string
}

variable "aws_region" {
  description = "AWS region for regional resources."
  type        = string
}

variable "notification_email" {
  description = "Email address subscribed to high-severity IAM Auditor alerts."
  type        = string
}

variable "schedule_expression" {
  description = "EventBridge schedule expression for the IAM Auditor Lambda."
  type        = string
}

variable "lambda_package_path" {
  description = "Path to the Lambda deployment zip generated by package.sh."
  type        = string
}

variable "lambda_source_hash" {
  description = "Base64 SHA256 hash for the Lambda deployment zip."
  type        = string
  default     = null
}

variable "lambda_timeout_seconds" {
  description = "Lambda timeout in seconds."
  type        = number
  default     = 300
}

variable "lambda_memory_size" {
  description = "Lambda memory size in MB."
  type        = number
  default     = 512
}

variable "permissions_boundary" {
  description = "Optional IAM permissions boundary ARN for the Lambda execution role."
  type        = string
  default     = null
}
