variable "project_name" {
  description = "Project name used for resource naming and tags."
  type        = string
}

variable "environment" {
  description = "Deployment environment name."
  type        = string
}

variable "notification_email" {
  description = "Email address subscribed to GuardDuty Processor SNS notifications."
  type        = string
}

variable "enable_guardduty" {
  description = "Whether to create and enable a GuardDuty detector in this region."
  type        = bool
  default     = false
}

variable "auto_remediate" {
  description = "Whether the processor may execute registered remediation playbooks."
  type        = bool
  default     = false
}

variable "dry_run" {
  description = "Hard kill switch. When true, remediation actions are logged but not executed."
  type        = bool
  default     = true
}

variable "slack_webhook_url" {
  description = "Optional Slack incoming webhook URL for notifications."
  type        = string
  default     = ""
  sensitive   = true
}

variable "lambda_package_path" {
  description = "Path to the Lambda deployment zip generated by package.sh."
  type        = string
}

variable "lambda_source_hash" {
  description = "Base64 SHA256 hash for the Lambda deployment zip."
  type        = string
  default     = null
}

variable "lambda_timeout_seconds" {
  description = "Lambda timeout in seconds."
  type        = number
  default     = 300
}

variable "lambda_memory_size" {
  description = "Lambda memory size in MB."
  type        = number
  default     = 512
}

variable "log_retention_days" {
  description = "CloudWatch log retention in days."
  type        = number
  default     = 30
}

variable "permissions_boundary" {
  description = "Optional IAM permissions boundary ARN for the Lambda execution role."
  type        = string
  default     = null
}
